import { Preset } from "./types";

export const PRESETS: Preset[] = [
  // ==========================================
  // 1. PELLICULES COULEUR AUTHENTIQUES (KODAK, FUJIFILM, AGFA)
  // ==========================================
  {
    id: "portra-160",
    label: "Kodak Portra 160",
    brand: "Kodak",
    blurb: "Grain ultra-fin, teints naturels, contraste doux pour la lumière naturelle",
    history: "Introduite par Kodak en 1998 pour succéder au Vericolor III. Sa technologie d'émulsion à cristaux T-Grain offre le grain le plus fin de la gamme Portra, optimisé pour numériser et révéler la texture soyeuse de la peau.",
    useCase: "Portraits en extérieur, mode, mariages, lumière naturelle éclatante, éditoriaux fine art.",
    famousArtists: ["Annie Leibovitz", "Ryan McGinley", "Mark Borthwick"],
    category: "vintage",
    hud: "leica",
    era: "1998",
    iso: 160,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 8,
      tint: 2,
      saturation: 4,
      contrast: -8,
      shadows: 14,
      highlights: -10,
      superContrast: 6,
      grain: 8,
      vignette: 6,
      fade: 6,
    },
  },
  {
    id: "portra-400",
    label: "Kodak Portra 400",
    brand: "Kodak",
    blurb: "Teints dorés légendaires, tons pastel chauds — le roi absolu du portrait",
    history: "La pellicule couleur négative la plus célèbre au monde, formulée à partir des coupleurs de colorants issus du cinéma Kodak Vision3. Elle offre une tolérance d'exposition légendaire de plus de 5 diaphragmes dans les hautes lumières.",
    useCase: "Portrait de studio et d'extérieur, éditoriaux de mode, street photography, scènes à fort contraste.",
    famousArtists: ["Juergen Teller", "Nan Goldin", "Alasdair McLellan", "Kendall Jenner"],
    category: "vintage",
    hud: "leica",
    era: "1998",
    iso: 400,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 14,
      tint: 4,
      saturation: 8,
      contrast: -6,
      shadows: 12,
      highlights: -8,
      superContrast: 8,
      grain: 12,
      vignette: 8,
      fade: 8,
      bloom: 10,
    },
  },
  {
    id: "portra-800",
    label: "Kodak Portra 800",
    brand: "Kodak",
    blurb: "Chaleur dorée poussée, grain organique généreux, basse lumière dorée",
    history: "Lancée en 1998 pour les photographes de défilés et de faible luminosité. Son émulsion multicouche optimise le rendu des ambiances dorées et préserve la texture de la peau même en lumière tamisée.",
    useCase: "Heure dorée tardive, ambiances nocturnes, concerts, scènes d'intérieur intimistes.",
    famousArtists: ["Gregory Crewdson", "Tim Walker", "Petra Collins"],
    category: "vintage",
    hud: "film",
    era: "1998",
    iso: 800,
    kelvin: 5200,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 20,
      saturation: 15,
      contrast: 8,
      shadows: 6,
      grain: 22,
      vignette: 14,
      fade: 12,
      halation: 18,
    },
  },
  {
    id: "ektar-100",
    label: "Kodak Ektar 100",
    brand: "Kodak",
    blurb: "Couleurs saturées ultra-vives, grain chirurgical le plus fin au monde",
    history: "Renaissance en 2008 de la célèbre marque Ektar lancée en 1989. Développée avec la technologie micro-cubique Kodak Vision, elle détient le record du grain le plus fin pour un négatif couleur (RMS 25).",
    useCase: "Photographie de paysage, nature, architecture, tirages grand format d'une netteté chirurgicale.",
    famousArtists: ["Peter Lik", "Alexey Titarenko", "Galen Rowell"],
    category: "vintage",
    hud: "film",
    era: "2008",
    iso: 100,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      saturation: 32,
      contrast: 22,
      superContrast: 18,
      sharpen: 18,
      shadows: -10,
      highlights: -4,
      grain: 6,
      vignette: 12,
    },
  },
  {
    id: "gold-200",
    label: "Kodak Gold 200",
    brand: "Kodak",
    blurb: "Nostalgie des albums 90s, tons chauds dorés, ombres bleutées",
    history: "Pellicule grand public culte des années 1980 et 1990 (anciennement Kodacolor Gold). Sa signature jaune-ambrée et son contraste chaleureux ont façonné la mémoire visuelle de toute une génération.",
    useCase: "Photographie du quotidien, voyages ensoleillés, vacances, nostalgie des années 90.",
    famousArtists: ["Martin Parr", "Stephen Shore", "William Eggleston"],
    category: "vintage",
    hud: "film",
    era: "1988",
    iso: 200,
    kelvin: 5600,
    aspectRatio: "3:2",
    dateStampDefault: true,
    adjustments: {
      temperature: 24,
      tintColor: [255, 230, 180],
      tintStrength: 10,
      saturation: 18,
      contrast: 14,
      grain: 16,
      vignette: 16,
      lightLeak: 12,
    },
  },
  {
    id: "colorplus-200",
    label: "Kodak ColorPlus 200",
    brand: "Kodak",
    blurb: "Chaleur vintage accessible, dominante jaune-ambrée décontractée",
    history: "L'une des émulsions les plus anciennes de Kodak toujours en production, héritière directe des formulations Kodacolor VR des années 1980. Elle produit des teintes chaudes légèrement cuivrées.",
    useCase: "Instantanés de rue décontractés, portraits spontanés, photos estivales.",
    famousArtists: ["Ren Hang", "Wolfgang Tillmans"],
    category: "vintage",
    hud: "film",
    era: "1990",
    iso: 200,
    kelvin: 5400,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 18,
      saturation: 12,
      contrast: 10,
      grain: 15,
      vignette: 14,
    },
  },
  {
    id: "kodachrome-64",
    label: "Kodachrome 64",
    brand: "Kodak",
    blurb: "Rouges profonds mythiques, noirs denses — la diapo National Geographic",
    history: "Formulée en 1935 par Leopold Godowsky et Leopold Mannes, puis modernisée en 1974 sous le procédé K-14. Dépourvue de coupleurs de couleur dans l'émulsion brute, elle garantissait une stabilité d'archivage centenaire et des rouges flamboyants.",
    useCase: "Reportage de voyage National Geographic, scènes de rue vibrantes, portraits emblématiques.",
    famousArtists: ["Steve McCurry (La Fille Afghane)", "William Eggleston", "Ernst Haas", "Saul Leiter"],
    category: "vintage",
    hud: "film",
    era: "1974",
    iso: 64,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 20,
      saturation: 25,
      contrast: 20,
      shadows: -15,
      grain: 15,
      vignette: 10,
      superContrast: 12,
    },
  },
  {
    id: "fuji-velvia-50",
    label: "Fuji Velvia 50",
    brand: "Fujifilm",
    blurb: "Verts émeraude et ciels pourpres saturés, contraste diapo implacable",
    history: "Sortie en 1990 (code RVP), Velvia a révolutionné la photographie de paysage grâce à sa saturation chromatique hyper-puissante, ses verts émeraude électriques et son contraste implacable sans aucun grain visible.",
    useCase: "Paysages grandioses, aurores et crépuscules, macrophotographie florale, faune sauvage.",
    famousArtists: ["Galen Rowell", "Frans Lanting", "Art Wolfe", "Peter Lik"],
    category: "vintage",
    hud: "hasselblad",
    era: "1990",
    iso: 50,
    kelvin: 5500,
    aspectRatio: "1:1",
    adjustments: {
      saturation: 40,
      contrast: 26,
      temperature: -6,
      tint: -8,
      superContrast: 18,
      shadows: -14,
      grain: 8,
      vignette: 18,
    },
  },
  {
    id: "fuji-velvia-100",
    label: "Fuji Velvia 100",
    brand: "Fujifilm",
    blurb: "Saturation chromatique maximale, ciels cobalt et feuillages éclatants",
    history: "Lancée en 2003 pour offrir la vivacité de Velvia 50 avec deux fois plus de sensibilité et une meilleure stabilité face à la lumière directe du soleil grâce aux coupleurs de colorants New-Generation E-6.",
    useCase: "Paysages sauvages, forêts luxuriantes, photographies de couchers de soleil marins.",
    famousArtists: ["Frans Lanting", "Jack Dykinga", "Carr Clifton"],
    category: "vintage",
    hud: "film",
    era: "2003",
    iso: 100,
    kelvin: 5600,
    aspectRatio: "3:2",
    adjustments: {
      saturation: 38,
      contrast: 24,
      temperature: -4,
      tint: -6,
      superContrast: 16,
      shadows: -12,
      grain: 7,
      vignette: 14,
    },
  },
  {
    id: "fuji-provia-100f",
    label: "Fuji Provia 100F",
    brand: "Fujifilm",
    blurb: "Neutralité chromatique exemplaire, rendu naturel fidèle des lumières du jour",
    history: "Inaugurée en 2000 avec la technologie Super Fine-Grain, Provia (RDPIII) est la diapositive E-6 professionnelle de référence mondiale pour sa neutralité chromatique absolue et sa réponse ultra-linéaire.",
    useCase: "Photographie commerciale, mode, reproduction d'œuvres d'art, architecture.",
    famousArtists: ["David LaChapelle", "Nick Knight", "Helmut Newton"],
    category: "vintage",
    hud: "pro",
    era: "2000",
    iso: 100,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      saturation: 12,
      contrast: 10,
      superContrast: 10,
      sharpen: 12,
      temperature: -2,
      grain: 6,
      vignette: 6,
    },
  },
  {
    id: "fuji-pro-400h",
    label: "Fuji Pro 400H",
    brand: "Fujifilm",
    blurb: "Tons pastel menthe et cyans laiteux, douceur lumineuse des mariages",
    history: "Pellicule professionnelle lancée en 2004 dotée d'une 4e couche sensible au cyan brevetée par Fujifilm. Elle capture les nuances pastel douces, les ciels laiteux et confère aux peaux une clarté lumineuse.",
    useCase: "Mariages haut de gamme, éditoriaux de mode fine art, portraits en lumière diffuse.",
    famousArtists: ["Jose Villa", "Elizabeth Messina", "KT Merry"],
    category: "vintage",
    hud: "leica",
    era: "2004",
    iso: 400,
    kelvin: 5600,
    aspectRatio: "3:2",
    adjustments: {
      temperature: -12,
      tint: -10,
      saturation: -6,
      contrast: -12,
      shadows: 18,
      highlights: 6,
      fade: 14,
      grain: 10,
      bloom: 12,
    },
  },
  {
    id: "fuji-superia",
    label: "Fuji Superia 400",
    brand: "Fujifilm",
    blurb: "Verts froids signature 4e couche, grain fin, parfait pour la rue",
    history: "Emulsion grand public polyvalente lancée en 1998, réputée pour sa réactivité sous éclairages mixtes et sa dominante verte-bleutée typique des villes japonaises la nuit.",
    useCase: "Photographie de rue nocturne, paysages urbains, reportages spontanés.",
    famousArtists: ["Daido Moriyama", "Nobuyoshi Araki", "Rinko Kawauchi"],
    category: "vintage",
    hud: "film",
    era: "1998",
    iso: 400,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      temperature: -8,
      tintColor: [210, 255, 225],
      tintStrength: 10,
      saturation: 10,
      grain: 8,
      contrast: 5,
    },
  },
  {
    id: "fuji-classic-chrome",
    label: "Fuji Classic Chrome",
    brand: "Fujifilm",
    blurb: "Tons documentaires désaturés, ciel bleu-vert profond, ombres denses",
    history: "Profil colorimétrique signature inspiré des reportages documentaires du XXe siècle des magazines Life et Paris Match. Il atténue la saturation globale tout en renforçant la densité des ombres.",
    useCase: "Photojournalisme, documentaire social, architecture urbaine, scènes de rue mélancoliques.",
    famousArtists: ["Fred Herzog", "Alex Webb", "Harry Gruyaert"],
    category: "vintage",
    hud: "leica",
    era: "2014",
    iso: 200,
    kelvin: 5400,
    aspectRatio: "3:2",
    adjustments: {
      saturation: -18,
      contrast: 18,
      shadows: -12,
      highlights: 6,
      superContrast: 14,
      temperature: -4,
      fade: 6,
      grain: 8,
      vignette: 12,
    },
  },
  {
    id: "agfa-vista-200",
    label: "Agfa Vista 200",
    brand: "Agfa",
    blurb: "Dominante vert-cyan caractéristique, rouges chaleureux et esprit vacances",
    history: "Fabriquée à Leverkusen en Allemagne dans les années 1990, Agfa Vista 200 se distingue par ses rouges profonds sur-saturés et sa teinte vert-cyan distinctive héritée des chimies Agfacolor.",
    useCase: "Photographie de voyage, paysages côtiers méditerranéens, architecture rétro.",
    famousArtists: ["Luigi Ghirri", "Franco Fontana"],
    category: "vintage",
    hud: "film",
    era: "1996",
    iso: 200,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      tintColor: [200, 255, 210],
      tintStrength: 15,
      saturation: 20,
      temperature: -10,
      contrast: 10,
      grain: 12,
    },
  },

  // ==========================================
  // 2. NOIR & BLANC ARGENTIQUE MYTHIQUE
  // ==========================================
  {
    id: "tri-x-400",
    label: "Kodak Tri-X 400",
    brand: "Kodak",
    blurb: "Légende du photojournalisme, grain mordant et noirs profonds",
    history: "Créée en 1954, Kodak Tri-X est le film noir et blanc le plus important de l'histoire de la photographie. Son grain mordant et sa dynamique sculpturale ont documenté toutes les révolutions du XXe siècle.",
    useCase: "Photojournalisme de guerre, street photography, portraits expressionnistes, scènes urbaines dures.",
    famousArtists: ["Henri Cartier-Bresson", "Garry Winogrand", "Sebastião Salgado", "Don McCullin", "Josef Koudelka"],
    category: "vintage",
    hud: "leica",
    era: "1954",
    iso: 400,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 32,
      grain: 30,
      shadows: -15,
      highlights: 8,
      superContrast: 20,
      sharpen: 12,
      vignette: 15,
    },
  },
  {
    id: "kodak-verichrome",
    label: "Kodak Verichrome Pan",
    brand: "Kodak",
    blurb: "L'émulsion orthopanchromatique légendaire de Vivian Maier",
    history: "Commercialisée de 1931 à 2002, Verichrome Pan possédait une double couche d'émulsion unique (une couche rapide et une couche lente) offrant une latitude d'exposition gigantesque et un velouté de gris onirique.",
    useCase: "Street photography intimiste, scènes de vie urbaine rétro, portraits à la lumière douce.",
    famousArtists: ["Vivian Maier", "Ansel Adams", "Imogen Cunningham"],
    category: "vintage",
    hud: "rolleiflex",
    era: "1931",
    iso: 125,
    aspectRatio: "1:1",
    adjustments: {
      monochrome: 100,
      contrast: 22,
      grain: 18,
      shadows: 10,
      highlights: -8,
      superContrast: 14,
      fade: 8,
      vignette: 12,
    },
  },
  {
    id: "tmax-3200",
    label: "Kodak T-Max P3200",
    brand: "Kodak",
    blurb: "Sensibilité extrême, grain tabulaire visible, ambiance concert & nuit",
    history: "Lancée en 1988 par Kodak, cette émulsion utilise des cristaux plats multi-zonés T-Grain pour atteindre des sensibilités extrêmes (jusqu'à ISO 25000 en poussé) dans l'obscurité quasi-totale.",
    useCase: "Concerts dans les clubs de jazz sombres, scènes de nuit clandestines, théâtre.",
    famousArtists: ["Anton Corbijn", "Jim Marshall", "Mick Rock"],
    category: "vintage",
    hud: "leica",
    era: "1988",
    iso: 3200,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 40,
      grain: 45,
      shadows: -18,
      highlights: 14,
      superContrast: 24,
    },
  },
  {
    id: "ilford-hp5",
    label: "Ilford HP5 Plus",
    brand: "Ilford",
    blurb: "Noir & blanc britannique classique, gamme de gris soyeuse",
    history: "Née en 1976 sous le nom HP5 puis améliorée en HP5 Plus en 1989 par Ilford à Mobberley en Angleterre. Célèbre pour sa latitude de pose infinie et sa palette de gris veloutée.",
    useCase: "Photographie de rue classique, portraits intimistes, paysages brumeux britanniques.",
    famousArtists: ["Bruce Gilden", "Jane Bown", "Elliott Erwitt"],
    category: "vintage",
    hud: "film",
    era: "1989",
    iso: 400,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 25,
      grain: 25,
      shadows: -10,
      highlights: -5,
      superContrast: 10,
    },
  },
  {
    id: "ilford-delta-3200",
    label: "Ilford Delta 3200 Pro",
    brand: "Ilford",
    blurb: "Grain atmosphérique géant, sensibilité nuit pour jazz clubs et pénombre",
    history: "Lancée en 1998 avec la technologie de cristaux Core-Shell d'Ilford. Elle sublime le grain argentique texturé et capture la magie des éclairages tamisés sans jamais boucher les ombres.",
    useCase: "Bars de jazz enfumés, street photography de nuit, concerts rock, atmosphères underground.",
    famousArtists: ["Bruce Gilden", "Anders Petersen", "Daido Moriyama"],
    category: "vintage",
    hud: "film",
    era: "1998",
    iso: 3200,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 36,
      grain: 50,
      shadows: -14,
      highlights: 16,
      superContrast: 26,
      vignette: 18,
    },
  },
  {
    id: "ilford-pan-f",
    label: "Ilford Pan F Plus 50",
    brand: "Ilford",
    blurb: "Grain soyeux quasi-invisible, contraste élevé et détails architecturaux",
    history: "Émulsion ultra-lente à grain extrêmement fin et très haute résolution, héritière des plaques photographiques de précision du milieu du XXe siècle.",
    useCase: "Architecture géométrique, natures mortes de studio, portraits posés en plein soleil.",
    famousArtists: ["Ansel Adams", "Edward Weston", "Michael Kenna"],
    category: "vintage",
    hud: "pro",
    era: "1992",
    iso: 50,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 34,
      grain: 4,
      superContrast: 18,
      sharpen: 22,
      shadows: -12,
    },
  },
  {
    id: "neopan-acros-100",
    label: "Fuji Neopan Acros 100 II",
    brand: "Fujifilm",
    blurb: "Grain technologique ultra-fin, pureté chirurgicale des dégradés japonais",
    history: "Produite au Japon par Fujifilm, Acros bénéficie de la technologie Super Fine-Σ grain offrant la plus haute résolution et la plus faible défaillance de réciprocité au monde pour les poses longues.",
    useCase: "Poses longues nocturnes, architecture contemporaine, micro-textures, street photography chirurgicale.",
    famousArtists: ["Daido Moriyama", "Hiroshi Sugimoto"],
    category: "vintage",
    hud: "pro",
    era: "2019",
    iso: 100,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 18,
      grain: 6,
      superContrast: 16,
      sharpen: 20,
      shadows: -4,
      highlights: 4,
    },
  },
  {
    id: "leica-monochrom",
    label: "Leica Monochrom",
    brand: "Leica",
    blurb: "Capteur sans matrice Bayer, piqué absolu et micro-contraste pur",
    history: "Révolution numérique de 2012 : Leica a retiré la matrice de filtres couleur de Bayer du capteur, capturant 100% de la luminance pure pour une netteté optique sans interpolation.",
    useCase: "Fine art, haute couture, tirages de collection grand format noir et blanc.",
    famousArtists: ["Ragnar Axelsson", "Ralph Gibson", "Jacob Aue Sobol"],
    category: "vintage",
    hud: "leica",
    era: "2015",
    iso: 320,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 30,
      grain: 5,
      sharpen: 20,
      superContrast: 22,
      shadows: -5,
    },
  },
  {
    id: "daguerreotype",
    label: "Daguerréotype 1839",
    brand: "Specialty",
    blurb: "Sépia XIXe originel, vignette lourde, portrait figé et pose lente",
    history: "Premier procédé photographique commercialisé au monde, présenté par Louis Daguerre et François Arago à l'Académie des Sciences de Paris en 1839. Image unique fixée sur plaque de cuivre argentée.",
    useCase: "Portraits historiques solennels, études d'antiquités, natures mortes intemporelles.",
    famousArtists: ["Louis Daguerre", "Nadar", "Southworth & Hawes"],
    category: "vintage",
    hud: "hasselblad",
    era: "1839",
    iso: 1,
    aspectRatio: "1:1",
    adjustments: {
      monochrome: 100,
      tintColor: [210, 180, 140],
      tintStrength: 70,
      vignette: 50,
      fade: 20,
      denoise: 15,
      contrast: 10,
    },
  },

  // ==========================================
  // 3. CINÉMA HOLLYWOOD 35MM & ÉMULSIONS ECN-2
  // ==========================================
  {
    id: "cinestill-800t",
    label: "CineStill 800T",
    brand: "CineStill",
    blurb: "Halos rouges nocturnes, équilibré tungstène 3200K, cinéma 35mm",
    history: "Émulsion cinéma Kodak Vision3 5219 500T dont la couche dorsale de carbone noir (Remjet) a été retirée pour permettre le développement en chimie photo C-41. Crée des halos rouges distinctifs autour des lumières.",
    useCase: "Photographie urbaine de nuit sous les néons, stations-service désertes, ambiance Blade Runner.",
    famousArtists: ["Gregory Crewdson", "Todd Hido", "Liam Wong"],
    category: "vintage",
    hud: "cinema",
    era: "2012",
    iso: 800,
    kelvin: 3200,
    aspectRatio: "16:9",
    adjustments: {
      tintColor: [255, 180, 150],
      tintStrength: 12,
      temperature: 10,
      shadows: -10,
      lightLeak: 15,
      grain: 18,
      contrast: 10,
      halation: 60,
      bloom: 24,
    },
  },
  {
    id: "cinestill-50d",
    label: "CineStill 50D Daylight",
    brand: "CineStill",
    blurb: "Émulsion cinéma 35mm lumière du jour : piqué chirurgical et halation subtile",
    history: "Version photographique sans remjet de la pellicule cinéma Kodak Vision3 50D 5203, utilisée pour les chefs-d'œuvre cinématographiques tournés en lumière du jour sous 50 ISO.",
    useCase: "Cinéma plein jour, portraits en extérieur ensoleillé, voitures de collection, paysages dorés.",
    famousArtists: ["Quentin Tarantino (Once Upon a Time in Hollywood)", "Christopher Nolan (Dunkirk)"],
    category: "vintage",
    hud: "cinema",
    era: "2015",
    iso: 50,
    kelvin: 5500,
    aspectRatio: "16:9",
    adjustments: {
      temperature: -4,
      contrast: 18,
      saturation: 14,
      superContrast: 16,
      sharpen: 20,
      halation: 22,
      grain: 6,
    },
  },
  {
    id: "arriflex-35bl",
    label: "Arriflex 35 BL Hollywood",
    brand: "ARRI",
    blurb: "Grain argentique 35mm cinéma, optiques Cooke Speed Panchro et cadence 24fps",
    history: "Caméra cinéma 35mm insonorisée légendaire d'ARRI sortie en 1972, ayant permis de tourner en son synchrone sur les tournages de Stanley Kubrick (Barry Lyndon, Shining) et Martin Scorsese (Taxi Driver).",
    useCase: "Photographie cinématique narrative, scènes de rue nocturnes, plans d'ambiance 2.39:1.",
    famousArtists: ["Stanley Kubrick", "Martin Scorsese", "Francis Ford Coppola"],
    category: "vintage",
    hud: "arriflex",
    era: "1972",
    iso: 500,
    kelvin: 4300,
    aspectRatio: "16:9",
    adjustments: {
      contrast: 15,
      saturation: 8,
      superContrast: 12,
      toneCurve: 35,
      remjetHalation: 25,
      acesToneMap: 20,
      grain: 16,
      vignette: 14,
    },
  },

  // ==========================================
  // 4. BOÎTIERS VINTAGE & MOYEN FORMAT MYTHIQUES
  // ==========================================
  {
    id: "linhof-technika-4x5",
    label: "Linhof Master Technika 4×5",
    brand: "Linhof",
    blurb: "Chambre grand format 4×5 allemande, bascule/décentrement et piqué monumental",
    history: "Le sommet de l'ingénierie mécanique photographique munichoise depuis 1936. Utilisée sur trépied avec plan-film 4×5 pouces pour corriger les perspectives architecturales et obtenir une profondeur de champ infinie.",
    useCase: "Architecture monumentale, paysages alpins grandioses, reproduction muséale.",
    famousArtists: ["Ansel Adams", "Julius Shulman", "Thomas Struth"],
    category: "vintage",
    hud: "linhof",
    era: "1972",
    iso: 64,
    kelvin: 5400,
    aspectRatio: "4:3",
    adjustments: {
      contrast: 22,
      superContrast: 28,
      sharpen: 35,
      shadows: 8,
      highlights: -12,
      dehaze: 15,
      grain: 4,
      vignette: 8,
    },
  },
  {
    id: "contax-t2-zeiss",
    label: "Contax T2 Carl Zeiss Sonnar",
    brand: "Contax",
    blurb: "Télémètre compact en titane, optique Carl Zeiss T* 38mm f/2.8 et look défilé",
    history: "Lancé par Kyocera et Carl Zeiss au Japon en 1990. Boîtier en titane indestructible et verre de précision T*, il est devenu l'appareil fétiche des plus grands photographes de mode et célébrités des années 90.",
    useCase: "Fashion backstage, soirées chic, portraits spontanés glamour, street photography de luxe.",
    famousArtists: ["Juergen Teller", "Mario Testino", "Terry Richardson", "Zendaya"],
    category: "vintage",
    hud: "contax",
    era: "1990",
    iso: 400,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      contrast: 18,
      saturation: 16,
      superContrast: 20,
      sharpen: 25,
      highlights: 12,
      bloom: 10,
      grain: 12,
      vignette: 14,
    },
  },
  {
    id: "mamiya-rb67",
    label: "Mamiya RB67 Pro SD 6×7",
    brand: "Mamiya",
    blurb: "L'icône studio moyen format 6×7, dos rotatif et optique Sekor C veloutée",
    history: "Surnommée 'la bête de studio' depuis 1970. Son négatif 6×7cm était presque 5 fois plus grand que le 35mm, offrant un modelé sculptural incomparable sur les couvertures de Vogue et Harper's Bazaar.",
    useCase: "Portraits de mode haute couture, éditoriaux studio, natures mortes de luxe.",
    famousArtists: ["Helmut Newton", "Richard Avedon", "Annie Leibovitz"],
    category: "vintage",
    hud: "mamiya",
    era: "1970",
    iso: 100,
    kelvin: 5200,
    aspectRatio: "4:3",
    adjustments: {
      contrast: 20,
      superContrast: 18,
      sharpen: 22,
      shadows: 14,
      highlights: -8,
      grain: 8,
      vignette: 10,
    },
  },
  {
    id: "nikon-f3-nasa",
    label: "Nikon F3 HP NASA",
    brand: "Nikon",
    blurb: "Le reflex pro indestructible des photojournalistes et des missions spatiales",
    history: "Dessiné par Giorgetto Giugiaro en 1980 avec sa célèbre bande rouge. Modifié par la NASA pour équiper les missions de la navette spatiale Discovery, il est le témoin visuel des événements majeurs de la fin du XXe siècle.",
    useCase: "Photojournalisme d'action, reportages extrêmes, scènes de rue rapides, exploration.",
    famousArtists: ["Steve McCurry", "David Burnett", "James Nachtwey"],
    category: "vintage",
    hud: "nikon",
    era: "1980",
    iso: 400,
    kelvin: 5400,
    aspectRatio: "3:2",
    adjustments: {
      contrast: 16,
      saturation: 14,
      superContrast: 18,
      sharpen: 20,
      grain: 12,
      vignette: 10,
    },
  },
  {
    id: "holga-120n",
    label: "Holga 120N Toy Camera",
    brand: "Lomography",
    blurb: "Lentille plastique 60mm, vignetage lourd, fuites de lumière et poésie brute",
    history: "Créée à Hong Kong en 1982 par T.M. Lee pour démocratiser le film 120 en Chine. Ses imperfections optiques (aberrations, vignetage, fuites de lumière) en ont fait le symbole mondial de la lomographie.",
    useCase: "Art contemporain, instantanés oniriques, séries photographiques poétiques et expérimentales.",
    famousArtists: ["David Burnett (Prix World Press Photo en Holga)", "Michael Kenna"],
    category: "vintage",
    hud: "holga",
    era: "1982",
    iso: 400,
    kelvin: 5500,
    aspectRatio: "1:1",
    adjustments: {
      contrast: 24,
      saturation: 18,
      vignette: 45,
      lightLeak: 25,
      chromaticAberration: 30,
      grain: 22,
      bloom: 15,
      fade: 12,
    },
  },
  {
    id: "olympus-pen-f",
    label: "Olympus Pen F Demi-Format",
    brand: "Olympus",
    blurb: "Reflex demi-cadre vertical 18×24mm, 72 poses par bobine et prisme rotatif",
    history: "Chef-d'œuvre du designer Yoshihisa Maitani en 1963. Premier reflex demi-format au monde, il exposait deux photos verticales de 18×24mm par vue 35mm standard, permettant 72 prises de vue par pellicule.",
    useCase: "Diptiques photographiques, récits visuels séquentiels, street photography discrète.",
    famousArtists: ["Eugene Smith", "Daido Moriyama"],
    category: "vintage",
    hud: "olympus",
    era: "1963",
    iso: 200,
    kelvin: 5400,
    aspectRatio: "3:2",
    adjustments: {
      contrast: 16,
      saturation: 10,
      superContrast: 14,
      grain: 18,
      vignette: 15,
      fade: 8,
    },
  },
  {
    id: "xpan-panoramic",
    label: "Hasselblad XPan 65:24",
    brand: "Hasselblad",
    blurb: "Format panoramique cinéma 65:24 légendaire, cadrage ultra-large",
    history: "Conçu conjointement par Hasselblad et Fujifilm en 1998, le XPan exposait une double vue 24×65mm sur pellicule 35mm standard, offrant un ratio panoramique cinéma de 2.7:1 sans recadrage.",
    useCase: "Paysages cinématiques épiques, récits documentaires immersifs, architecture monumentale.",
    famousArtists: ["Josef Koudelka", "Peter Bialobrzeski", "Nick Brandt"],
    category: "vintage",
    hud: "xpan",
    era: "1998",
    iso: 400,
    aspectRatio: "65:24",
    adjustments: {
      contrast: 18,
      saturation: 12,
      superContrast: 16,
      grain: 14,
      vignette: 20,
      temperature: 6,
    },
  },
  {
    id: "polaroid-sx70",
    label: "Polaroid SX-70 Instant",
    brand: "Polaroid",
    blurb: "Blancs délavés, fuite de lumière chimique, instantané mythique",
    history: "Le chef-d'œuvre d'Edwin Land en 1972 : le premier appareil reflex instantané pliant au monde, éjectant une photo à développement chimique autonome sous les yeux de l'utilisateur.",
    useCase: "Portraits d'artistes intimistes, carnets de voyage spontanés, art contemporain.",
    famousArtists: ["Andy Warhol", "Helmut Newton", "David Hockney", "Walker Evans"],
    category: "vintage",
    hud: "polaroid",
    era: "1972",
    iso: 150,
    kelvin: 5500,
    aspectRatio: "1:1",
    filmBorder: "polaroid",
    adjustments: {
      fade: 35,
      temperature: 15,
      contrast: -10,
      saturation: -10,
      vignette: 25,
      lightLeak: 20,
      grain: 10,
      bloom: 18,
      filmBorder: "polaroid",
    },
  },
  {
    id: "lomo-metropolis",
    label: "LomoChrome Metropolis",
    brand: "Lomography",
    blurb: "Désaturation métallique sélective, ombres vert de gris et contraste rude",
    history: "Formulée en 2019 par Lomography, Metropolis est la première nouvelle émulsion couleur créée depuis plus de 10 ans. Elle désature les tons moyens tout en conservant des noirs profonds et des rouges vifs.",
    useCase: "Architecture industrielle brute, exploration urbaine (Urbex), scènes de rue dystopiques.",
    famousArtists: ["Lomography Collective", "Brandon Woelfel"],
    category: "vintage",
    hud: "film",
    era: "2019",
    iso: 400,
    kelvin: 5200,
    aspectRatio: "3:2",
    adjustments: {
      saturation: -25,
      contrast: 24,
      superContrast: 20,
      shadows: -15,
      highlights: 10,
      grain: 18,
      vignette: 18,
    },
  },
  {
    id: "lomo-purple",
    label: "LomoChrome Purple XR",
    brand: "Lomography",
    blurb: "Virage psychédélique : la chlorophylle et les verts deviennent violet fuchsia",
    history: "Inspirée du Kodak Aerochrome infrarouge, cette formule chimique spéciale transmute les longueurs d'onde vertes en teintes violettes et pourpres intenses tout en gardant les tons de peau naturels.",
    useCase: "Forêts enchantées, paysages floraux surréalistes, séances de portrait fantastique.",
    famousArtists: ["Paolo Pettigiani", "Lomo Arts"],
    category: "vintage",
    hud: "film",
    era: "2013",
    iso: 400,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      infrared: 85,
      saturation: 30,
      contrast: 20,
      grain: 15,
      vignette: 16,
    },
  },
  {
    id: "polaroid-duochrome",
    label: "Polaroid Duochrome Noir & Jaune",
    brand: "Polaroid",
    blurb: "Bicolore expérimental haute tension : ombres d'encre et rehauts jaune cadmium",
    history: "Pellicule instantanée expérimentale issue des ateliers de sauvetage The Impossible Project à Enschede. Elle remplace les colorants CMY par un pigment bicolore jaune et noir graphique.",
    useCase: "Graphisme urbain, affiches de concert, portraits expressionnistes contrastés.",
    famousArtists: ["Maurizio Galimberti", "Impossible Lab Project"],
    category: "vintage",
    hud: "polaroid",
    era: "2016",
    iso: 640,
    aspectRatio: "1:1",
    filmBorder: "polaroid",
    adjustments: {
      monochrome: 90,
      tintColor: [255, 220, 0],
      tintStrength: 80,
      contrast: 40,
      shadows: -20,
      highlights: 20,
      grain: 20,
      filmBorder: "polaroid",
    },
  },

  // ==========================================
  // 5. FILTRES CURIEUX, BIZARRES & EXPÉRIMENTAUX
  // ==========================================
  {
    id: "aerochrome-ir",
    label: "Kodak Aerochrome EIR",
    brand: "Kodak",
    blurb: "Infrarouge militaire : la chlorophylle et la végétation deviennent rouge rubis",
    history: "Film infrarouge fausse couleur développé par Kodak dans les années 1940 pour la reconnaissance militaire de l'armée américaine, afin de débusquer le camouflage ennemi. La végétation y apparaît rouge carmin.",
    useCase: "Paysages oniriques extraterrestres, reportages environnementaux surréalistes, mode avant-garde.",
    famousArtists: ["Richard Mosse (The Enclave)", "David San Millán"],
    category: "curious",
    hud: "cinema",
    era: "1971",
    iso: 400,
    adjustments: {
      infrared: 90,
      contrast: 25,
      saturation: 30,
      vignette: 20,
      grain: 15,
    },
  },
  {
    id: "flir-thermal",
    label: "Vision Thermique FLIR",
    brand: "Specialty",
    blurb: "Spectre de chaleur Predator / caméra infrarouge Ironbow",
    history: "Algorithme d'imagerie thermique utilisé par les caméras de vision nocturne militaire FLIR et rendu célèbre par le film Predator (1987). Mappe les températures de surface du bleu glacial au rouge incandescent.",
    useCase: "Expérimentations visuelles, esthétique techno-industrielle, portraits thermiques.",
    famousArtists: ["John McTiernan (Predator)", "Trevor Paglen"],
    category: "curious",
    hud: "thermal",
    era: "2010",
    iso: 800,
    adjustments: {
      thermal: 100,
      contrast: 30,
      superContrast: 20,
    },
  },
  {
    id: "nvg-pvs14",
    label: "Vision Nocturne PVS-14",
    brand: "Specialty",
    blurb: "Phosphore vert Gen-3, tube cathodique et amplification de photons",
    history: "Monoculaire de vision nocturne militaire standard de l'armée américaine utilisant des tubes intensificateurs de lumière à l'arséniure de gallium (Gen 3).",
    useCase: "Scènes d'action nocturnes, infiltration urbaine, esthétique tactique militaire.",
    famousArtists: ["Denis Villeneuve (Sicario)", "Kathryn Bigelow (Zero Dark Thirty)"],
    category: "curious",
    hud: "nvg",
    era: "2000",
    iso: 6400,
    adjustments: {
      nightVision: 95,
      grain: 35,
      scanlines: 20,
      bloom: 30,
    },
  },
  {
    id: "vhs-glitch",
    label: "VHS Glitch 1989",
    brand: "Specialty",
    blurb: "Bande magnétique usée, décrochage de tracking, décalage chromatique et neige",
    history: "Emulation des artefacts analogiques des magnétoscopes VHS des années 80 : étirement des têtes de lecture, désynchronisation des lignes et bruit de bande magnétique.",
    useCase: "Vaporwave, clips musicaux rétro, esthétique Y2K, courts-métrages d'horreur analogique.",
    famousArtists: ["Harmony Korine", "Oneohtrix Point Never"],
    category: "curious",
    hud: "glitch",
    era: "1989",
    iso: 400,
    adjustments: {
      glitch: 70,
      chromaticAberration: 50,
      scanlines: 60,
      saturation: -15,
      grain: 25,
    },
  },
  {
    id: "prism-kaleidoscope",
    label: "Prisme Kaléidoscope",
    brand: "Specialty",
    blurb: "Réfraction optique 6 facettes éclatées et symétries psychédéliques",
    history: "Inspiré des filtres à facettes rotatives en cristal utilisés dans les années 1960 et 1970 pour les pochettes de disques vinyles psychédéliques.",
    useCase: "Clips musicaux, scènes de rêve, mode avant-gardiste, abstractions géométriques.",
    famousArtists: ["Pink Floyd Artworks", "Mick Rock"],
    category: "curious",
    hud: "cinema",
    era: "1969",
    iso: 200,
    adjustments: {
      kaleidoscope: 90,
      saturation: 25,
      contrast: 15,
      bloom: 20,
    },
  },
  {
    id: "sabattier-solarize",
    label: "Solarisation Sabattier",
    brand: "Specialty",
    blurb: "Effet Man Ray : inversion partielle des tons en plein développement",
    history: "Découvert par Armand Sabattier en 1860 et élevé au rang d'art par Man Ray et Lee Miller en 1931. Une réexposition brève à la lumière pendant le bain de révélateur inverse les densités.",
    useCase: "Portraits surréalistes, nus artistiques, silhouettes graphiques d'avant-garde.",
    famousArtists: ["Man Ray", "Lee Miller", "Maurice Tabard"],
    category: "curious",
    hud: "film",
    era: "1931",
    iso: 100,
    adjustments: {
      solarize: 85,
      monochrome: 80,
      contrast: 25,
      grain: 20,
    },
  },
  {
    id: "cyanotype-1842",
    label: "Cyanotype 1842",
    brand: "Specialty",
    blurb: "Tirage photographique d'époque au bleu de Prusse (blueprint)",
    history: "Inventé par le scientifique et astronome britannique Sir John Herschel en 1842. Utilisé par Anna Atkins pour créer le premier livre illustré de photographies de l'histoire (algues britanniques).",
    useCase: "Herbiers botaniques, études architecturales, tirages d'art historiques.",
    famousArtists: ["Anna Atkins", "Sir John Herschel"],
    category: "curious",
    hud: "film",
    era: "1842",
    iso: 5,
    aspectRatio: "1:1",
    adjustments: {
      cyanotype: 95,
      contrast: 20,
      vignette: 30,
      fade: 10,
    },
  },
  {
    id: "gameboy-camera",
    label: "GameBoy Camera 1998",
    brand: "Specialty",
    blurb: "Capteur CMOS 128×112, tramage 2-bit vert monochrome rétro-gaming pur",
    history: "Accessoire culte de Nintendo lancé en 1998, reconnu par le Livre Guinness des Records comme le plus petit appareil photo numérique au monde à sa sortie.",
    useCase: "Pixel art rétro, portraits 8-bit insolites, nostalgie gaming des années 90.",
    famousArtists: ["Neil Young (pochette d'album Silver & Gold)", "Nintendo R&D"],
    category: "curious",
    hud: "gameboy",
    era: "1998",
    iso: 200,
    aspectRatio: "4:3",
    adjustments: {
      dither: 95,
      contrast: 40,
      grain: 30,
    },
  },
  {
    id: "sony-mavica",
    label: "Sony Mavica Disquette 3.5\"",
    brand: "Sony",
    blurb: "Capteur CCD 640×480, stockage direct sur disquette 1.44 Mo et look Y2K",
    history: "Lancée par Sony en 1997 (MVC-FD5/FD7). Elle enregistrait directement les images JPEG sur de véritables disquettes informatiques 3.5 pouces, inaugurant l'ère numérique grand public.",
    useCase: "Esthétique cybernétique fin des années 90, blogs Y2K, instantanés lo-fi rétro.",
    famousArtists: ["Internet Archive Artists", "Net-Art Creators"],
    category: "vintage",
    hud: "mavica",
    era: "1997",
    iso: 100,
    aspectRatio: "4:3",
    adjustments: {
      contrast: 15,
      saturation: 15,
      sharpen: 25,
      highlights: 18,
      chromaticAberration: 14,
      grain: 8,
    },
  },

  // ==========================================
  // 6. SCÈNES PROFESSIONNELLES & BOÎTIERS MODERNES
  // ==========================================
  {
    id: "portrait-studio-85mm",
    label: "Portrait Studio 85mm",
    brand: "Pro Master",
    blurb: "Teint soyeux, micro-bloom lumineux, F1.4 flatteur et ombres délicatement débouchées",
    history: "Conçu selon les standards optiques des objectifs 85mm f/1.4 Planar et GM : séparation des plans tridimensionnelle, adoucissement optique des micro-imperfections et transition de flou picturale.",
    useCase: "Portraits de studio, mode, beauté, gros plans expressifs.",
    famousArtists: ["Peter Lindbergh", "Mario Testino", "Platon"],
    category: "pro-scenes",
    hud: "pro",
    iso: 100,
    kelvin: 5400,
    aspectRatio: "3:2",
    adjustments: {
      shadows: 18,
      highlights: -12,
      contrast: -6,
      saturation: 8,
      temperature: 6,
      tint: 2,
      bloom: 16,
      superContrast: 10,
      sharpen: 12,
      vignette: 14,
    },
  },
  {
    id: "portrait-golden-hour",
    label: "Portrait Golden Glow",
    brand: "Pro Master",
    blurb: "Lumière dorée rasante, carnation rayonnante et éclat chaleureux du soleil couchant",
    history: "Calibré sur la température spectrale des rayons solaires au crépuscule (2800K-3500K) avec un léger débouchage des contre-jours pour magnifier les reflets dans la chevelure.",
    useCase: "Séances de couple en extérieur, fin de journée à la plage, portraits romantiques.",
    famousArtists: ["Chris Burkard", "Brandon Woelfel"],
    category: "pro-scenes",
    hud: "pro",
    iso: 100,
    kelvin: 5800,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 24,
      tint: 4,
      saturation: 14,
      highlights: 8,
      shadows: 12,
      bloom: 20,
      vignette: 12,
      superContrast: 8,
    },
  },
  {
    id: "portrait-monochrome-fineart",
    label: "Portrait Studio N&B Fine Art",
    brand: "Pro Master",
    blurb: "Noir & blanc dramatique façon Peter Lindbergh — ombres sculptées et regard perçant",
    history: "Inspiré de l'école de portraiture éditoriale allemande : contraste local accru sur les yeux et la structure osseuse, sans artifice de lissage numérique.",
    useCase: "Portraits d'acteurs de caractère, musiciens, éditoriaux de magazine noir et blanc.",
    famousArtists: ["Peter Lindbergh", "Irving Penn", "Platon"],
    category: "pro-scenes",
    hud: "pro",
    iso: 100,
    kelvin: 5000,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 28,
      shadows: -14,
      highlights: 12,
      sharpen: 30,
      superContrast: 22,
      vignette: 18,
      grain: 8,
    },
  },
  {
    id: "hasselblad-x2d-100c",
    label: "Hasselblad X2D 100C",
    brand: "Hasselblad",
    blurb: "Moyen format 100 Mégapixels, solution couleur naturelle HNCS 16-bit et piqué chirurgical",
    history: "Le summum du moyen format numérique contemporain de Göteborg. Sa science des couleurs Hasselblad Natural Colour Solution (HNCS) garantit des transitions tonales d'une fluidité inégalée.",
    useCase: "Photographie de paysage d'exposition, art contemporain, haute joaillerie, architecture.",
    famousArtists: ["Ming Thein", "Tom Oldham"],
    category: "pro-scenes",
    hud: "hasselblad",
    era: "2024",
    iso: 64,
    kelvin: 5200,
    aspectRatio: "4:3",
    adjustments: {
      contrast: 14,
      superContrast: 22,
      sharpen: 38,
      shadows: 12,
      highlights: -12,
      dehaze: 15,
      toneCurve: 30,
      saturation: 6,
    },
  },
  {
    id: "leica-m11-pro",
    label: "Leica M11 Pro Rangefinder",
    brand: "Leica",
    blurb: "Télémètre d'exception 60MP, optique Summilux-M 35mm f/1.4 ASPH et 'Leica Look'",
    history: "L'héritier moderne de l'Ur-Leica de 1914 d'Oskar Barnack. Capteur BSI triple résolution et rendu chromatique Wetzlar légendaire privilégiant la clarté et le micro-contraste des ombres.",
    useCase: "Street photography discrète, photojournalisme haut de gamme, carnets de voyage de luxe.",
    famousArtists: ["Sebastião Salgado", "Bruce Gilden", "Craig Semetko"],
    category: "pro-scenes",
    hud: "leica",
    era: "2024",
    iso: 64,
    kelvin: 5400,
    aspectRatio: "3:2",
    adjustments: {
      contrast: 18,
      superContrast: 30,
      sharpen: 35,
      shadows: 6,
      highlights: -10,
      saturation: 10,
      vignette: 12,
      toneCurve: 28,
    },
  },
  {
    id: "sony-alpha-1",
    label: "Sony α1 Flagship Mirrorless",
    brand: "Sony",
    blurb: "Capteur plein format 50.1MP empilé, autofocus temps réel et profil S-Cinetone",
    history: "Le vaisseau amiral de Sony alliant capteur Exmor RS ultra-rapide et colorimétrie cinéma S-Cinetone issue des caméras Venice de Hollywood.",
    useCase: "Sport professionnel, faune sauvage en mouvement rapide, reportage d'action.",
    famousArtists: ["Mikael Buck", "Terry Donnelly"],
    category: "pro-scenes",
    hud: "sony-alpha",
    era: "2024",
    iso: 100,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      contrast: 12,
      superContrast: 20,
      sharpen: 30,
      shadows: 10,
      highlights: -10,
      saturation: 10,
      toneCurve: 25,
    },
  },
  {
    id: "arri-alexa-35",
    label: "ARRI ALEXA 35 LogC4",
    brand: "ARRI",
    blurb: "La caméra référence des Oscars : dynamique 17 stops et science de couleur REVEAL",
    history: "Considérée par les directeurs de la photographie du monde entier comme la meilleure caméra numérique de l'histoire du cinéma, avec sa colorimétrie LogC4 et sa restitution parfaite de la peau.",
    useCase: "Longs métrages de cinéma, séries premium, publicités de luxe, clips d'exception.",
    famousArtists: ["Roger Deakins (1917, Blade Runner 2049)", "Greig Fraser (Dune, The Batman)"],
    category: "pro-scenes",
    hud: "arri-alexa",
    era: "2023",
    iso: 800,
    kelvin: 5600,
    aspectRatio: "16:9",
    adjustments: {
      contrast: 14,
      saturation: 12,
      superContrast: 16,
      toneCurve: 40,
      remjetHalation: 15,
      acesToneMap: 35,
    },
  },
  {
    id: "red-v-raptor-8k",
    label: "RED V-RAPTOR 8K VV",
    brand: "RED",
    blurb: "Capteur VistaVision 8K grand format, REDCODE RAW et cadence 120fps",
    history: "Caméra cinéma de pointe utilisée pour les productions hollywoodiennes à grand spectacle nécessitant une résolution et une netteté géométriques extrêmes.",
    useCase: "Blockbusters, séquences d'action ultra-ralenties, cinéma de science-fiction.",
    famousArtists: ["David Fincher (Mank, The Killer)", "Zack Snyder"],
    category: "pro-scenes",
    hud: "red-cinema",
    era: "2023",
    iso: 800,
    kelvin: 5600,
    aspectRatio: "16:9",
    adjustments: {
      contrast: 20,
      saturation: 14,
      superContrast: 24,
      sharpen: 25,
      toneCurve: 35,
      acesToneMap: 30,
    },
  },
  // ==========================================
  // 7. APPAREILS EXOTIQUES & CAPTEURS SCIENTIFIQUES
  // ==========================================
  {
    id: "jwst-nircam",
    label: "James Webb Space Telescope (NIRCam)",
    brand: "NASA",
    blurb: "Diffraction hexagonale 6 branches, spectre infrarouge profond et fond cosmique",
    history: "Lancé le 25 décembre 2021 au point de Lagrange L2 (1,5 million de km de la Terre), le télescope spatial James Webb utilise un miroir primaire en béryllium plaqué or de 6,5 m. Ses instruments NIRCam et MIRI révèlent les premières galaxies de l'univers avec une résolution infrarouge sans précédent.",
    useCase: "Astrophotographie, scènes nocturnes à forts points lumineux, paysages célestes, rendus cosmiques surréalistes.",
    famousArtists: ["NASA / ESA / CSA", "Dr. Jane Rigby", "Piliers de la Création (2022)"],
    category: "curious",
    hud: "jwst",
    era: "2022",
    iso: 3200,
    kelvin: 3200,
    aspectRatio: "1:1",
    adjustments: {
      jwstSpikes: 85,
      contrast: 25,
      shadows: -15,
      highlights: 30,
      superContrast: 20,
      dehaze: 40,
    },
  },
  {
    id: "phase-one-iq4",
    label: "Phase One IQ4 150MP Achromatic",
    brand: "Phase One",
    blurb: "Capteur BSI moyen format 151 mégapixels sans matrice de Bayer — pureté absolue du noir et blanc",
    history: "Le capteur moyen format numérique le plus résolu et coûteux du monde (53.4 x 40.0mm). Dépourvu de filtre de Bayer et de filtre passe-bas, chaque photosite capte 100% du flux lumineux, offrant une plage dynamique colossale de 15 diaphragmes et un micro-contraste inégalable.",
    useCase: "Architecture monumentale, reproduction d'art, paysages texturés, tirages d'exposition géants.",
    famousArtists: ["Daniel Berehulak", "Reuben Wu", "Sandro Miller"],
    category: "pro-scenes",
    hud: "phase-one",
    era: "2020",
    iso: 200,
    kelvin: 5600,
    aspectRatio: "4:3",
    adjustments: {
      monochrome: 100,
      casSharpness: 80,
      superContrast: 35,
      contrast: 18,
      sharpen: 30,
      toneCurve: 25,
    },
  },
  {
    id: "electron-microscope",
    label: "Microscope Électronique à Balayage (SEM)",
    brand: "Scientific",
    blurb: "Topographie nanométrique par électrons secondaires, contraste sous vide et micro-relief 45,000x",
    history: "Inventé par Manfred von Ardenne en 1937 et perfectionné par Charles Oatley à Cambridge. Au lieu de photons, un canon à émission de champ (FEG) bombarde l'échantillon d'un faisceau d'électrons de 20 kV dans une chambre à vide, révélant la structure atomique 3D.",
    useCase: "Macro extrême, textures minérales et organiques, entomologie, nanotechnologie, abstraction scientifique.",
    famousArtists: ["Lennart Nilsson (Life)", "Susumu Nishinaga", "David Scharf"],
    category: "curious",
    hud: "sem",
    era: "1965",
    iso: 100,
    kelvin: 6500,
    aspectRatio: "4:3",
    adjustments: {
      electronMicro: 90,
      macroBoost: 60,
      superContrast: 45,
      contrast: 30,
      sharpen: 25,
    },
  },
  {
    id: "kirlian-aura",
    label: "Électrophotographie Kirlian (Haute Tension)",
    brand: "Scientific",
    blurb: "Décharge plasma coronale haute tension, halo bioluminescent violet et cyan ionisé",
    history: "Découverte en 1939 par Semyon et Valentina Kirlian en URSS. En appliquant un champ électrique oscillant haute tension (25 kV, 50 kHz) à travers une plaque diélectrique, les gaz environnants s'ionisent pour former une couronne luminescente spectaculaire.",
    useCase: "Portraits ésotériques et mystiques, art conceptuel, photographie botanique, pochettes d'albums psychédéliques.",
    famousArtists: ["Thelma Moss (The Probability of the Impossible)", "David Bowie (Earthling Album Art)"],
    category: "curious",
    hud: "kirlian",
    era: "1939",
    iso: 400,
    kelvin: 4500,
    aspectRatio: "1:1",
    adjustments: {
      kirlianAura: 90,
      bloom: 40,
      contrast: 40,
      shadows: -30,
      superContrast: 20,
    },
  },
  {
    id: "lidar-mesh",
    label: "LiDAR Solid-State 3D (Spatial Computing)",
    brand: "Scientific",
    blurb: "Maillage spatial 3D temps de vol, isolignes bathymétriques et nuage de points holographique",
    history: "Technologie optique de télédétection par laser pulsé à 905nm. Utilisée dans l'aérospatiale, les véhicules autonomes et les casques de réalité mixte pour cartographier l'environnement en 3D volumétrique instantané.",
    useCase: "Cyberpunk, cartographie spatiale urbaine, scènes futuristes, modélisation 3D de volumes.",
    famousArtists: ["Radiohead (House of Cards Video - James Frost)", "ScanLAB Projects"],
    category: "curious",
    hud: "lidar",
    era: "2024",
    iso: 800,
    kelvin: 5600,
    aspectRatio: "16:9",
    adjustments: {
      lidarMesh: 85,
      superContrast: 30,
      contrast: 25,
      casSharpness: 50,
    },
  },
  {
    id: "quantum-event-horizon",
    label: "Horizon du Trou Noir (EHT Gravitational)",
    brand: "Scientific",
    blurb: "Lentille gravitationnelle relativiste d'Einstein, effet Doppler asymétrique et anneau de photons",
    history: "Inspiré de l'interférométrie à très longue base (VLBI) de l'Event Horizon Telescope qui a capturé en 2019 la première image historique du trou noir M87* et Sagittarius A* au centre de notre galaxie.",
    useCase: "Rendus cosmiques surréalistes, distorsions spatio-temporelles, art abstrait de science-fiction.",
    famousArtists: ["Event Horizon Telescope Collaboration", "Kip Thorne (Interstellar / Gargantua Visual FX)"],
    category: "curious",
    hud: "blackhole",
    era: "2019",
    iso: 6400,
    kelvin: 3200,
    aspectRatio: "1:1",
    adjustments: {
      quantumEvent: 90,
      contrast: 35,
      saturation: 20,
      bloom: 25,
    },
  },
  {
    id: "solar-h-alpha",
    label: "Télescope Solaire H-Alpha (656.3nm)",
    brand: "Scientific",
    blurb: "Filtration interférométrique Fabry-Pérot étalon, éruptions chromosphériques et filaments de plasma",
    history: "Optique solaire équipée d'un étalon à bande passante ultra-étroite (< 0.5Å) centrée sur la raie d'émission de l'hydrogène à 656.28nm, bloquant 99.999% de la photosphère pour révéler les protubérances et filaments magnétiques du Soleil.",
    useCase: "Photographie solaire, couchers de soleil flamboyants, textures de feu, abstraction chromatique carmin.",
    famousArtists: ["Alan Friedman", "Andrew McCarthy (Cosmic Background)", "Thierry Legault"],
    category: "curious",
    hud: "solar-halpha",
    era: "2015",
    iso: 100,
    kelvin: 2500,
    aspectRatio: "1:1",
    adjustments: {
      solarHAlpha: 95,
      contrast: 30,
      superContrast: 40,
      dehaze: 25,
    },
  },
  {
    id: "lytro-illum",
    label: "Lytro Illum Plénoptique 4D",
    brand: "Lytro",
    blurb: "Matrice de micro-lentilles 40 Mégarays pour refocalisation 4D a posteriori et bokeh multidimensionnel",
    history: "Développée par Ren Ng à Stanford en 2014. Contrairement aux capteurs 2D classiques, un réseau de 400 000 micro-lentilles capture la direction de chaque rayon lumineux incident, permettant de changer le plan de mise au point après la prise de vue.",
    useCase: "Portraits à profondeur de champ variable, compositions multicouches, expérimentations optiques 4D.",
    famousArtists: ["Ren Ng", "Vincent Laforet (Mobius Project)"],
    category: "curious",
    hud: "lytro",
    era: "2014",
    iso: 100,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      tiltShift: 40,
      superContrast: 20,
      casSharpness: 45,
      bloom: 15,
      acesToneMap: 25,
    },
  },
  {
    id: "medical-sonogram",
    label: "Échographie Doppler Médicale (3.5MHz)",
    brand: "Scientific",
    blurb: "Transducteur piézoélectrique à ultrasons, vélocimétrie Doppler couleur et écho-texture acoustique",
    history: "Basée sur la réflexion d'ondes sonores à haute fréquence (2-15 MHz) et l'effet Doppler pour mesurer le flux sanguin et visualiser la dynamique des tissus en temps réel.",
    useCase: "Imagerie médicale stylisée, art acoustique, textures organiques abstraites, ambiances cliniques.",
    famousArtists: ["Dr. Ian Donald", "Art in Science Collective"],
    category: "curious",
    hud: "sonogram",
    era: "1985",
    iso: 400,
    kelvin: 6500,
    aspectRatio: "4:3",
    adjustments: {
      monochrome: 60,
      tintColor: [80, 160, 255],
      tintStrength: 70,
      superContrast: 45,
      contrast: 35,
      dither: 15,
    },
  },
  {
    id: "cyber-recon-drone",
    label: "Drone Tactique Recon UAV (Optique EO/IR)",
    brand: "Specialty",
    blurb: "Gimbal optronique 3-axes, télémétrie avionique militaire et verrouillage laser de cibles",
    history: "Système d'imagerie électro-optique embarqué sur drone de reconnaissance moderne avec incrustation télémétrique en temps réel, visée laser et amplification des contrastes critiques.",
    useCase: "Street photography tactique, ambiances cyber-militaires, paysages industriels et d'architecture aérienne.",
    famousArtists: ["Trevor Paglen", "Tomas van Houtryve (Blue Sky Days)"],
    category: "pro-scenes",
    hud: "drone-hud",
    era: "2025",
    iso: 1600,
    kelvin: 5600,
    aspectRatio: "16:9",
    adjustments: {
      dehaze: 45,
      casSharpness: 60,
      superContrast: 30,
      contrast: 20,
      acesToneMap: 35,
    },
  },
];

export function getPreset(id: string | null): Preset | null {
  return PRESETS.find((p) => p.id === id) ?? null;
}

export const PRO_SCENE_PRESETS = PRESETS.filter((p) => p.category === "pro-scenes");
export const VINTAGE_PRESETS = PRESETS.filter((p) => p.category === "vintage");
export const CURIOUS_PRESETS = PRESETS.filter((p) => p.category === "curious");
export const MODERN_PRESETS = PRESETS.filter((p) => p.category === "modern");
