import { Preset } from "./types";

export const PRESETS: Preset[] = [
  // ==========================================
  // PELLICULES COULEUR (KODAK, FUJIFILM, AGFA)
  // ==========================================
  {
    id: "portra-160",
    label: "Kodak Portra 160",
    brand: "Kodak",
    blurb: "Grain ultra-fin, teints naturels, contraste doux pour la lumière naturelle",
    category: "vintage",
    hud: "leica",
    era: "1998",
    iso: 160,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 8,
      tint: 2,
      saturation: 4,
      contrast: -8,
      shadows: 14,
      highlights: -10,
      superContrast: 6,
      grain: 8,
      vignette: 6,
      fade: 6,
    },
  },
  {
    id: "portra-400",
    label: "Kodak Portra 400",
    brand: "Kodak",
    blurb: "Teints dorés légendaires, tons pastel chauds — le roi absolu du portrait",
    category: "vintage",
    hud: "leica",
    era: "1998",
    iso: 400,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 14,
      tint: 4,
      saturation: 8,
      contrast: -6,
      shadows: 12,
      highlights: -8,
      superContrast: 8,
      grain: 12,
      vignette: 8,
      fade: 8,
      bloom: 10,
    },
  },
  {
    id: "portra-800",
    label: "Kodak Portra 800",
    brand: "Kodak",
    blurb: "Chaleur dorée poussée, grain organique généreux, basse lumière dorée",
    category: "vintage",
    hud: "film",
    era: "1998",
    iso: 800,
    kelvin: 5200,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 20,
      saturation: 15,
      contrast: 8,
      shadows: 6,
      grain: 22,
      vignette: 14,
      fade: 12,
      halation: 18,
    },
  },
  {
    id: "ektar-100",
    label: "Kodak Ektar 100",
    brand: "Kodak",
    blurb: "Couleurs saturées ultra-vives, grain chirurgical le plus fin au monde",
    category: "vintage",
    hud: "film",
    era: "2008",
    iso: 100,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      saturation: 32,
      contrast: 22,
      superContrast: 18,
      sharpen: 18,
      shadows: -10,
      highlights: -4,
      grain: 6,
      vignette: 12,
    },
  },
  {
    id: "gold-200",
    label: "Kodak Gold 200",
    brand: "Kodak",
    blurb: "Nostalgie des albums 90s, tons chauds dorés, ombres bleutées",
    category: "vintage",
    hud: "film",
    era: "1988",
    iso: 200,
    kelvin: 5600,
    aspectRatio: "3:2",
    dateStampDefault: true,
    adjustments: {
      temperature: 24,
      tintColor: [255, 230, 180],
      tintStrength: 10,
      saturation: 18,
      contrast: 14,
      grain: 16,
      vignette: 16,
      lightLeak: 12,
    },
  },
  {
    id: "colorplus-200",
    label: "Kodak ColorPlus 200",
    brand: "Kodak",
    blurb: "Chaleur vintage accessible, dominante jaune-ambrée décontractée",
    category: "vintage",
    hud: "film",
    era: "1990",
    iso: 200,
    kelvin: 5400,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 18,
      saturation: 12,
      contrast: 10,
      grain: 15,
      vignette: 14,
    },
  },
  {
    id: "kodachrome-64",
    label: "Kodachrome 64",
    brand: "Kodak",
    blurb: "Rouges profonds mythiques, noirs denses — la diapo National Geographic",
    category: "vintage",
    hud: "film",
    era: "1974",
    iso: 64,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      temperature: 20,
      saturation: 25,
      contrast: 20,
      shadows: -15,
      grain: 15,
      vignette: 10,
      superContrast: 12,
    },
  },
  {
    id: "fuji-velvia-50",
    label: "Fuji Velvia 50",
    brand: "Fujifilm",
    blurb: "Verts émeraude et ciels pourpres saturés, contraste diapo implacable",
    category: "vintage",
    hud: "hasselblad",
    era: "1990",
    iso: 50,
    kelvin: 5500,
    aspectRatio: "1:1",
    adjustments: {
      saturation: 40,
      contrast: 26,
      temperature: -6,
      tint: -8,
      superContrast: 18,
      shadows: -14,
      grain: 8,
      vignette: 18,
    },
  },
  {
    id: "fuji-provia-100f",
    label: "Fuji Provia 100F",
    brand: "Fujifilm",
    blurb: "Neutralité chromatique exemplaire, rendu naturel fidèle des lumières du jour",
    category: "vintage",
    hud: "pro",
    era: "2000",
    iso: 100,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      saturation: 12,
      contrast: 10,
      superContrast: 10,
      sharpen: 12,
      temperature: -2,
      grain: 6,
      vignette: 6,
    },
  },
  {
    id: "fuji-pro-400h",
    label: "Fuji Pro 400H",
    brand: "Fujifilm",
    blurb: "Tons pastel menthe et cyans laiteux, douceur lumineuse des mariages",
    category: "vintage",
    hud: "leica",
    era: "2004",
    iso: 400,
    kelvin: 5600,
    aspectRatio: "3:2",
    adjustments: {
      temperature: -12,
      tint: -10,
      saturation: -6,
      contrast: -12,
      shadows: 18,
      highlights: 6,
      fade: 14,
      grain: 10,
      bloom: 12,
    },
  },
  {
    id: "fuji-superia",
    label: "Fuji Superia 400",
    brand: "Fujifilm",
    blurb: "Verts froids signature 4e couche, grain fin, parfait pour la rue",
    category: "vintage",
    hud: "film",
    era: "1998",
    iso: 400,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      temperature: -8,
      tintColor: [210, 255, 225],
      tintStrength: 10,
      saturation: 10,
      grain: 8,
      contrast: 5,
    },
  },
  {
    id: "fuji-classic-chrome",
    label: "Fuji Classic Chrome",
    brand: "Fujifilm",
    blurb: "Tons documentaires désaturés, ciel bleu-vert profond, ombres denses",
    category: "vintage",
    hud: "leica",
    era: "2014",
    iso: 200,
    kelvin: 5400,
    aspectRatio: "3:2",
    adjustments: {
      saturation: -18,
      contrast: 18,
      shadows: -12,
      highlights: 6,
      superContrast: 14,
      temperature: -4,
      fade: 6,
      grain: 8,
      vignette: 12,
    },
  },
  {
    id: "agfa-vista",
    label: "Agfa Vista 200",
    brand: "Agfa",
    blurb: "Dominante vert-cyan caractéristique, rouges gonflés",
    category: "vintage",
    hud: "film",
    era: "1996",
    iso: 200,
    kelvin: 5500,
    aspectRatio: "3:2",
    adjustments: {
      tintColor: [200, 255, 210],
      tintStrength: 15,
      saturation: 20,
      temperature: -10,
      contrast: 10,
      grain: 12,
    },
  },

  // ==========================================
  // NOIR & BLANC ARGENTIQUE (B&W FILM)
  // ==========================================
  {
    id: "tri-x-400",
    label: "Kodak Tri-X 400",
    brand: "Kodak",
    blurb: "Légende du photojournalisme, grain mordant et noirs profonds",
    category: "vintage",
    hud: "leica",
    era: "1954",
    iso: 400,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 32,
      grain: 30,
      shadows: -15,
      highlights: 8,
      superContrast: 20,
      sharpen: 12,
      vignette: 15,
    },
  },
  {
    id: "tmax-3200",
    label: "Kodak T-Max P3200",
    brand: "Kodak",
    blurb: "Sensibilité extrême, grain tabulaire visible, ambiance concert & nuit",
    category: "vintage",
    hud: "leica",
    era: "1988",
    iso: 3200,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 40,
      grain: 45,
      shadows: -18,
      highlights: 14,
      superContrast: 24,
    },
  },
  {
    id: "ilford-hp5",
    label: "Ilford HP5 Plus",
    brand: "Ilford",
    blurb: "Noir & blanc britannique classique, gamme de gris soyeuse",
    category: "vintage",
    hud: "film",
    era: "1989",
    iso: 400,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 25,
      grain: 25,
      shadows: -10,
      highlights: -5,
      superContrast: 10,
    },
  },
  {
    id: "ilford-pan-f",
    label: "Ilford Pan F Plus 50",
    brand: "Ilford",
    blurb: "Grain soyeux quasi-invisible, contraste élevé et détails architecturaux",
    category: "vintage",
    hud: "pro",
    era: "1992",
    iso: 50,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 34,
      grain: 4,
      superContrast: 18,
      sharpen: 22,
      shadows: -12,
    },
  },
  {
    id: "neopan-acros-100",
    label: "Fuji Neopan Acros 100",
    brand: "Fujifilm",
    blurb: "Grain technologique ultra-fin, pureté chirurgicale des dégradés",
    category: "vintage",
    hud: "pro",
    era: "2002",
    iso: 100,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 18,
      grain: 6,
      superContrast: 16,
      sharpen: 20,
      shadows: -4,
      highlights: 4,
    },
  },
  {
    id: "leica-monochrom",
    label: "Leica Monochrom",
    brand: "Leica",
    blurb: "Capteur sans matrice Bayer, piqué absolu et micro-contraste pur",
    category: "vintage",
    hud: "leica",
    era: "2015",
    iso: 320,
    aspectRatio: "3:2",
    adjustments: {
      monochrome: 100,
      contrast: 30,
      grain: 5,
      sharpen: 20,
      superContrast: 22,
      shadows: -5,
    },
  },
  {
    id: "daguerreotype",
    label: "Daguerréotype 1839",
    brand: "Specialty",
    blurb: "Sépia XIXe originel, vignette lourde, portrait figé et pose lente",
    category: "vintage",
    hud: "hasselblad",
    era: "1839",
    iso: 1,
    aspectRatio: "1:1",
    adjustments: {
      monochrome: 100,
      tintColor: [210, 180, 140],
      tintStrength: 70,
      vignette: 50,
      fade: 20,
      denoise: 15,
      contrast: 10,
    },
  },

  // ==========================================
  // CINÉMA & FORMATS LÉGENDAIRES
  // ==========================================
  {
    id: "cinestill-800t",
    label: "CineStill 800T",
    brand: "CineStill",
    blurb: "Halos rouges nocturnes, équilibré tungstène 3200K, cinéma 35mm",
    category: "vintage",
    hud: "cinema",
    era: "2012",
    iso: 800,
    kelvin: 3200,
    aspectRatio: "16:9",
    adjustments: {
      tintColor: [255, 180, 150],
      tintStrength: 12,
      temperature: 10,
      shadows: -10,
      lightLeak: 15,
      grain: 18,
      contrast: 10,
      halation: 60,
      bloom: 24,
    },
  },
  {
    id: "cinestill-50d",
    label: "CineStill 50D",
    brand: "CineStill",
    blurb: "Film cinéma 50 ISO lumière du jour, teintes dorées et halation subtile",
    category: "vintage",
    hud: "cinema",
    era: "2015",
    iso: 50,
    kelvin: 5500,
    aspectRatio: "16:9",
    adjustments: {
      temperature: 16,
      saturation: 18,
      contrast: 16,
      superContrast: 12,
      grain: 10,
      halation: 35,
      bloom: 15,
      vignette: 10,
    },
  },
  {
    id: "xpan-panoramic",
    label: "Hasselblad XPan",
    brand: "Hasselblad",
    blurb: "Format panoramique cinéma 65:24 légendaire, cadrage ultra-large",
    category: "vintage",
    hud: "xpan",
    era: "1998",
    iso: 400,
    aspectRatio: "65:24",
    adjustments: {
      contrast: 18,
      saturation: 12,
      superContrast: 16,
      grain: 14,
      vignette: 20,
      temperature: 6,
    },
  },
  {
    id: "polaroid-sx70",
    label: "Polaroid SX-70",
    brand: "Polaroid",
    blurb: "Blancs délavés, fuite de lumière chimique, instantané mythique",
    category: "vintage",
    hud: "hasselblad",
    era: "1972",
    iso: 150,
    kelvin: 5500,
    aspectRatio: "1:1",
    filmBorder: "polaroid",
    adjustments: {
      fade: 35,
      temperature: 15,
      contrast: -10,
      saturation: -10,
      vignette: 25,
      lightLeak: 20,
      grain: 10,
      bloom: 18,
      filmBorder: "polaroid",
    },
  },

  // ==========================================
  // FILTRES CURIEUX, BIZARRES & EXPÉRIMENTAUX
  // ==========================================
  {
    id: "aerochrome-ir",
    label: "Kodak Aerochrome EIR",
    brand: "Kodak",
    blurb: "Infrarouge militaire : la chlorophylle et la végétation deviennent rouge rubis",
    category: "curious",
    hud: "cinema",
    era: "1971",
    iso: 400,
    adjustments: {
      infrared: 90,
      contrast: 25,
      saturation: 30,
      vignette: 20,
      grain: 15,
    },
  },
  {
    id: "flir-thermal",
    label: "Vision Thermique FLIR",
    brand: "Specialty",
    blurb: "Spectre de chaleur Predator / caméra infrarouge Ironbow",
    category: "curious",
    hud: "thermal",
    era: "2010",
    iso: 800,
    adjustments: {
      thermal: 100,
      contrast: 30,
      superContrast: 20,
    },
  },
  {
    id: "nvg-pvs14",
    label: "Vision Nocturne PVS-14",
    brand: "Specialty",
    blurb: "Phosphore vert Gen-3, tube cathodique et amplification de photons",
    category: "curious",
    hud: "nvg",
    era: "2000",
    iso: 6400,
    adjustments: {
      nightVision: 95,
      grain: 35,
      scanlines: 20,
      bloom: 30,
    },
  },
  {
    id: "vhs-glitch",
    label: "VHS Glitch 1989",
    brand: "Specialty",
    blurb: "Bande magnétique usée, décrochage de tracking, décalage chromatique et neige",
    category: "curious",
    hud: "glitch",
    era: "1989",
    iso: 400,
    adjustments: {
      glitch: 70,
      chromaticAberration: 50,
      scanlines: 60,
      saturation: -15,
      grain: 25,
    },
  },
  {
    id: "prism-kaleidoscope",
    label: "Prisme Kaléidoscope",
    brand: "Specialty",
    blurb: "Réfraction optique 6 facettes éclatées et symétries psychédéliques",
    category: "curious",
    hud: "cinema",
    era: "1969",
    iso: 200,
    adjustments: {
      kaleidoscope: 90,
      saturation: 25,
      contrast: 15,
      bloom: 20,
    },
  },
  {
    id: "sabattier-solarize",
    label: "Solarisation Sabattier",
    brand: "Specialty",
    blurb: "Effet Man Ray : inversion partielle des tons en plein développement",
    category: "curious",
    hud: "film",
    era: "1931",
    iso: 100,
    adjustments: {
      solarize: 85,
      monochrome: 80,
      contrast: 25,
      grain: 20,
    },
  },
  {
    id: "cyanotype-1842",
    label: "Cyanotype 1842",
    brand: "Specialty",
    blurb: "Tirage photographique d'époque au bleu de Prusse (blueprint)",
    category: "curious",
    hud: "film",
    era: "1842",
    iso: 5,
    aspectRatio: "1:1",
    adjustments: {
      cyanotype: 95,
      contrast: 20,
      vignette: 30,
      fade: 10,
    },
  },
  {
    id: "gameboy-camera",
    label: "GameBoy Camera 1998",
    brand: "Specialty",
    blurb: "Capteur CMOS 128×112, tramage 2-bit vert monochrome rétro-gaming pur",
    category: "curious",
    hud: "cctv",
    era: "1998",
    iso: 200,
    aspectRatio: "4:3",
    adjustments: {
      dither: 95,
      contrast: 40,
      grain: 30,
    },
  },
  {
    id: "cybershot-y2k",
    label: "Sony Cyber-shot Y2K",
    brand: "Specialty",
    blurb: "Capteur CCD 2000s, couleurs acidulées, flash direct et date rétro",
    category: "vintage",
    hud: "digicam",
    era: "2002",
    iso: 100,
    aspectRatio: "4:3",
    dateStampDefault: true,
    adjustments: {
      exposure: 8,
      contrast: 18,
      saturation: 25,
      sharpen: 30,
      highlights: 22,
      temperature: -4,
      chromaticAberration: 12,
    },
  },
  {
    id: "disposable-flash",
    label: "Jetable + Flash",
    brand: "Specialty",
    blurb: "Hautes lumières cramées, grain dur, soirée 2003",
    category: "vintage",
    hud: "film",
    era: "1998",
    iso: 800,
    kelvin: 5800,
    dateStampDefault: true,
    adjustments: { highlights: 35, exposure: 10, temperature: -15, grain: 35, contrast: 15, saturation: -5 },
  },
  {
    id: "vhs",
    label: "Caméscope VHS",
    brand: "Specialty",
    blurb: "Lignes de balayage, aberration chromatique",
    category: "vintage",
    hud: "camcorder",
    era: "1985",
    iso: 400,
    kelvin: 4300,
    adjustments: { scanlines: 60, chromaticAberration: 40, saturation: -30, denoise: 25, contrast: -10, temperature: -5 },
  },
  {
    id: "security-cam",
    label: "Caméra de surveillance",
    brand: "Specialty",
    blurb: "Vert monochrome, grain lourd, 3h du matin",
    category: "vintage",
    hud: "cctv",
    era: "2005",
    iso: 3200,
    adjustments: { monochrome: 100, tintColor: [150, 255, 150], tintStrength: 60, grain: 30, scanlines: 30, contrast: -15, exposure: -5 },
  },
  {
    id: "dashcam",
    label: "Dashcam",
    brand: "Specialty",
    blurb: "Grand-angle froid, hautes lumières cramées, l'œil qui ne cligne jamais",
    category: "vintage",
    hud: "dashcam",
    iso: 200,
    kelvin: 6000,
    adjustments: { temperature: -12, contrast: 8, saturation: -12, highlights: -20, shadows: -10, vignette: 25, grain: 12, denoise: 15, chromaticAberration: 12 },
  },
  {
    id: "video-doorbell",
    label: "Sonnette connectée",
    brand: "Specialty",
    blurb: "Grand-angle doux, HDR plat, quelqu'un sonne à la porte",
    category: "vintage",
    hud: "doorbell",
    iso: 400,
    kelvin: 6500,
    adjustments: { contrast: -8, shadows: 15, highlights: -15, saturation: -8, vignette: 35, chromaticAberration: 15, denoise: 12, sharpen: 10, temperature: -5 },
  },
  {
    id: "webcam",
    label: "Webcam",
    brand: "Specialty",
    blurb: "Compression basse, teint chaud, réunion qui aurait pu être un e-mail",
    category: "vintage",
    hud: "webcam",
    iso: 400,
    kelvin: 5000,
    adjustments: { temperature: 8, saturation: 10, contrast: 5, denoise: 22, vignette: 12, grain: 8, highlights: -8 },
  },

  // ==========================================
  // FILTRES MODERNES
  // ==========================================
  {
    id: "vivid-pop",
    label: "Vivid Pop",
    blurb: "Couleurs punchy, contraste net — le feed qui claque",
    category: "modern",
    hud: "modern",
    adjustments: { saturation: 30, contrast: 15, sharpen: 20, highlights: -5, superContrast: 12 },
  },
  {
    id: "clarte-urbaine",
    label: "Clarté Urbaine",
    blurb: "Contraste froid et net, béton et verre",
    category: "modern",
    hud: "pro",
    adjustments: { contrast: 20, saturation: 10, tintColor: [200, 220, 255], tintStrength: 8, sharpen: 15, superContrast: 16 },
  },
  {
    id: "chaleur-doree",
    label: "Chaleur Dorée",
    blurb: "Golden hour instantané, peau et ciel dorés",
    category: "modern",
    hud: "modern",
    adjustments: { temperature: 25, highlights: 10, fade: 10, saturation: 10, bloom: 14 },
  },
  {
    id: "noir-contraste",
    label: "Noir Contrasté",
    blurb: "N&B moderne, ombres qui claquent",
    category: "modern",
    hud: "pro",
    adjustments: { monochrome: 100, contrast: 35, sharpen: 25, shadows: -15, superContrast: 20 },
  },
  {
    id: "pastel-doux",
    label: "Pastel Doux",
    blurb: "Tons délavés, hautes lumières relevées, tout en douceur",
    category: "modern",
    hud: "modern",
    adjustments: { fade: 30, saturation: -15, highlights: 15, contrast: -10, bloom: 12 },
  },
  {
    id: "neon-nuit",
    label: "Néon Nuit",
    blurb: "Magenta et cyan, ville la nuit, léger halo",
    category: "modern",
    hud: "cinema",
    adjustments: {
      tintColor: [255, 110, 220],
      tintStrength: 18,
      contrast: 20,
      saturation: 20,
      shadows: -10,
      vignette: 20,
      chromaticAberration: 10,
      halation: 30,
    },
  },
  {
    id: "teint-naturel",
    label: "Teint Naturel",
    blurb: "\"Pas de filtre\" mais en mieux — à peine retouché",
    category: "modern",
    hud: "modern",
    adjustments: { contrast: 8, saturation: 5, sharpen: 10, denoise: 10, superContrast: 6 },
  },
];

export function getPreset(id: string | null): Preset | null {
  return PRESETS.find((p) => p.id === id) ?? null;
}

export const VINTAGE_PRESETS = PRESETS.filter((p) => p.category === "vintage");
export const CURIOUS_PRESETS = PRESETS.filter((p) => p.category === "curious");
export const MODERN_PRESETS = PRESETS.filter((p) => p.category === "modern");
